export enum AppTypes {
    HOME = "Chăm sóc làn da, Chăm sóc vẻ đẹp của bạn",
    DESCRIPTION = "Chào mừng bạn đến với trang chủ của nền tảng thương mại điện tử của chúng tôi. Khám phá sản phẩm và tận hưởng trải nghiệm mua sắm!",
    PRODUCTS = "Sản phẩm",
    CART = "Giỏ hàng",
    CHECKOUT = "Thanh toán",
    ORDER_HISTORY = "Lịch sử đơn hàng",
    PROFILE = "Hồ sơ",
    WISHLIST = "Danh sách yêu thích",
    SUPPORT = "Hỗ trợ",
    SETTINGS = "Cài đặt",
    ABOUT_US = "Về chúng tôi",
    CONTACT_US = "Liên hệ",
    SKIN_CONCERN = "Sản phẩm hỗ trợ",
    SHOP_CATEGORIES = "Sản phẩm dành cho da của bạn",
    DISCOVER = "KHÁM PHÁ SKINVIA FLAGSHIP",
    DISCOVER_DESC = "Tìm kiếm sự kết hợp lý tưởng giữa các liệu trình tại phòng khám và chế độ chăm sóc da.",
    LOREM_IPSUM = "Sản phẩm chất lượng cao",
    NO_DATA = "Không có dữ liệu",
    FINDING = "Tìm kiếm"
}
