export enum HomeTypes {
    HOME = "Care For Your Skin, Care For Your Beauty",
    DESCRIPTION = "Welcome to the home page of our e-commerce platform. Explore our products and enjoy your shopping experience!",
    PRODUCTS = "products",
    CART = "cart",
    CHECKOUT = "checkout",
    ORDER_HISTORY = "orderHistory",
    PROFILE = "profile",
    WISHLIST = "wishlist",
    SUPPORT = "support",
    SETTINGS = "settings",
    ABOUT_US = "aboutUs",
    CONTACT_US = "contactUs",
    SKIN_CONCERN = "Shop by Skin Concerns",
    SHOP_CATEGORIES = "Shop by Categories",
    DISCOVER = "DISCOVER A SKINVIA FLAGSHIP",
    DISCOVER_DESC = "Find your ideal combination of in-office treatments & skincare regimens.",
    LOREM_IPSUM = "Lorem Ipsum Dolor Sit Amet",
}
